org = "rust-lang"
name = "llvm-project"
description = "Rust-specific fork of LLVM."
bots = []

[access.teams]
wg-llvm = "maintain"

[[branch-protections]]
pattern = "rustc/*"
pr-required = false

[[branch-protections]]
pattern = "master"
pr-required = false
