org = "rust-lang"
name = "rustc-dev-guide"
description = "A guide to how rustc works and how to contribute to it."
homepage = "https://rustc-dev-guide.rust-lang.org"
bots = ["rustbot"]

[access.teams]
bootstrap = "write"
compiler = "write"
wg-rustc-dev-guide = "maintain"
infra = "write"
libs = "write"
libs-contributors = "write"

[[branch-protections]]
pattern = "master"
ci-checks = ["ci"]
required-approvals = 0

# This branch protection exists for historical reasons
# We had to force-push the whole commit history of rustc-dev-guide
# This branch contains the old commit graph, to keep commit references working
[[branch-protections]]
pattern = "master-old"
